DROP TABLE IF EXISTS CLIENT_ZONE;
DROP TABLE IF EXISTS COURIER_ZONE;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ZONE;
DROP TABLE IF EXISTS COURIER;

CREATE TABLE CLIENT
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    USERNAME VARCHAR(20) NOT NULL,
    FIO VARCHAR(50) NOT NULL,
    ADRESS TEXT NOT NULL,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    PRIMARY KEY(ID, USERNAME)
);

CREATE TABLE ZONE
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    DISTRICT VARCHAR (50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE COURIER
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    FIO VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    PASSWORD_HASH VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID, PHONE_NUMBER)
);

CREATE TABLE CLIENT_ZONE
(
    CLIENT_ID INT NOT NULL,
    CLIENT_USERNAME VARCHAR(20) NOT NULL,
    ZONE_ID INT NOT NULL,
    FOREIGN KEY (CLIENT_ID, CLIENT_USERNAME) REFERENCES CLIENT (ID, USERNAME),
    FOREIGN KEY (ZONE_ID) REFERENCES ZONE (ID),
    PRIMARY KEY (CLIENT_ID, CLIENT_USERNAME, ZONE_ID)
);

CREATE TABLE COURIER_ZONE
(
    COURIER_ID INT NOT NULL,
    COURIER_PHONE_NUMBER VARCHAR(20) NOT NULL,
    ZONE_ID INT NOT NULL,
    FOREIGN KEY (COURIER_ID, COURIER_PHONE_NUMBER) REFERENCES COURIER (ID, PHONE_NUMBER),
    FOREIGN KEY (ZONE_ID) REFERENCES ZONE (ID),
    PRIMARY KEY (COURIER_ID, COURIER_PHONE_NUMBER, ZONE_ID)
);

CREATE TABLE RESTAURANT
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    REST_NAME VARCHAR(50) NOT NULL,
    ADRES TEXT NOT NULL,
    PRIMARY KEY (ID)
)

CREATE TABLE RESTAURANT_ZONE
(
    RESTAURANT_ID INT NOT NULL,
    ZONE_ID INT NOT NULL,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT (ID),
    FOREIGN KEY (ZONE_ID) REFERENCES ZONE (ID),
    PRIMARY KEY (RESTAURANT_ID, ZONE_ID)
);

CREATE TABLE MENU
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    DISH VARCHAR (50) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE RESTAURANT_MENU
(
    RESTAURANT_ID INT NOT NULL,
    DISH_ID INT NOT NULL,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANT(ID),
    FOREIGN KEY (DISH_ID) REFERENCES MENU(ID),
    PRIMARY KEY (RESTAURANT_ID, DISH_ID)
);



CREATE TABLE INGRIDIENTS
(
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    ING_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE MENU_INGRIDIENTS
(
    INGRIDIENT_ID INT NOT NULL,
    DISH_ID INT NOT NULL,
    FOREIGN KEY (INGRIDIENT_ID) REFERENCES INGRIDIENTS(ID),
    FOREIGN KEY (DISH_ID) REFERENCES MENU(ID),
    PRIMARY KEY (INGRIDIENT_ID, DISH_ID)
);

CREATE TABLE CART
(   
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    CLIENT_ID INT NOT NULL,
    CLIENT_USERNAME VARCHAR(20) NOT NULL,
    FOREIGN KEY (CLIENT_ID, CLIENT_USERNAME) REFERENCES CLIENT (ID, USERNAME),
    PRIMARY KEY(ID)
);

CREATE TABLE POSITION
(
    CART_ID INT NOT NULL,
    DISH_ID INT NOT NULL,
    COUNT INT NOT NULL,
    OFFER_ID INT DEFAULT NULL,
    FOREIGN KEY (CART_ID) REFERENCES CART(ID),
    FOREIGN KEY (DISH_ID) REFERENCES MENU(ID),
    FOREIGN KEY (OFFER_ID) REFERENCES OFFER(ID),
    PRIMARY KEY (CART_ID, DISH_ID)
);

CREATE TABLE OFFER
(
    CLIENT_ID INT NOT NULL,
    CLIENT_USERNAME VARCHAR(20) NOT NULL,
    COURIER_ID INT DEFAULT NULL,
    COURIER_PHONE_NUMBER VARCHAR(20) DEFAULT NULL,
    DAYDATE DATE NOT NULL,
    DELIVERY BOOLEAN NOT NULL DEFAULT false,
    DELIVERED BOOLEAN NOT NULL DEFAULT false,
    ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (CLIENT_ID, CLIENT_USERNAME) REFERENCES CLIENT(ID, USERNAME),
    FOREIGN KEY (COURIER_ID, COURIER_PHONE_NUMBER) REFERENCES COURIER(ID, PHONE_NUMBER)
);




